class SettingsLocators:
    AutoconnectSwitch = 'qa-toggle-autoconnect'
    AutoconnectSwitchColor = '//*[@id="qa-toggle-autoconnect"]/div'
    AdBlockerSwitch = 'qa-toggle-block-ads'
    CookiesSwitch = 'qa-toggle-cookies'
    TrackersSwitch = 'qa-toggle-trackers'
    TrackersSwitchColor = '//*[@id="qa-toggle-trackers"]/div'
    TrackersIconColor = 'qa-icon-trackers'
    HistorySwitch = 'qa-toggle-history'
    HistorySwitchColor = '//*[@id="qa-toggle-history"]/div'
    HistoryIconSVG = 'qa-icon-history'
    SmartFiltersSwitch = 'qa-toggle-filters'
    ConsentCookies = '/html/body/div/div[6]/div/div/div[4]/button'
    GoBackButton = 'head__button'
    AppStoreButton = 'qa-settings-stores-app-store'
    PlayMarketButton = 'qa-settings-stores-google-play'
    AppGalleryButton = 'qa-settings-stores-app-gallery'
    AmazonMarketButton = 'qa-settings-stores-amazon'
    QRCode = 'settings-stores__qr'
    SmartFiltersInputSearch = 'qa-filters-search'
    AdBlockerSwitchColorGreen = '//*[@id="qa-toggle-block-ads"]/div'



class ReloadPopUpLocators:
    CloseNotification = 'qa-notification-close'
    TextNotification = 'qa-notification-text'
    ReloadButton = 'qa-notification-reload'
    MANAGE_BUTTON = 'qa-manage-blocker'
    WEB_SITE_INPUT = 'qa-search-field'
    ADD_WEB_SITE_BUTTON = 'qa-add-button'
    INCORRECT_SITE_TEXT = 'v-toast'
    SETTINGS_TITLE = 'qa-head-settings'
    INPUT_SEARCH_SITE = '//input[@placeholder="Search"]'
    ERROR_TEXT_ALERT = 'v-toast__text'
    DELETE_WEBSITE_BUTTON_X = 'list-items__icon'
    RELOAD_NOW_POP_UP = 'notification__btn'
    X_BUTTON = 'notification__close'
    SWITCHER_BUTTON = '/html/body/div/div[1]/div/div[1]/div/div[2]/div[1]/div/div[2]/div[1]/label/div'
    SMART_FILTERS_ICON = 'qa-icon-smart-filters'
    SMART_FILTERS_SWITCH = '//*[@id="qa-toggle-filters"]/div'
    MANAGE_BUTTON_SMART_FILTERS  = 'qa-manage-filters'
    ADD_WEB_SITE_BUTTON_SMART_FILTERS = 'qa-filters-form-add-btn'
    SMART_FILTERS_ICON_FOR_WEBSITE = 'qa-icon-vpn'
    FILTERS_TO_APPLY = 'qa-filters-apply'
    ENTER_WEB_SITE_INPUT = 'qa-search-field'
    SMART_FILTER_CONDITIONS = 'qa-filters-conditions'
    BUTTON_LABEL = 'qa-button-label'
    SWITCHER_VPN_TEXT = 'qa-switcher-name-vpn'
    SWITCHER_TOGGLE_BLOCK_ADS = 'qa-switcher-toggle-block-ads'
    SWITCHER_TOGGLE_DONT_SAVE_HISTORY = 'qa-switcher-toggle-dont-save-history'
    SWITCHER_TOGGLE_DENY_COOKIES = 'qa-switcher-toggle-deny-cookies'
    SWITCHER_TOGGLE_BLOCK_TRACKERS = 'qa-switcher-toggle-block-tracker'
    BUTTON_SAVE = 'qa-button-save'
    ADD_WEBSITE_AVAILABLE_BUTTON_TEXT = 'qa-filters-add-info'
    ITEM_SITE_4 = '//*[contains(text(), "example4.com")]'
    ITEM_SITE_2 = '//*[contains(text(), "example2.com")]'
    ITEM_SITE_3 = '//*[contains(text(), "example3.com")]'
    ITEM_SITE = '//*[contains(text(), "example.com")]'
    BUTTON_REMOVE = 'list-items__icon'
    BUTTON_DELETE_SITE = 'qa-modal-btn-remove'
    MODAL_SUBTITLE = 'qa-modal-subtitle'
    SMART_FILTERS_FOR_WEBSITE_TITLE = 'qa-head-filters'
    FILTERS_TITLE = 'qa-filters-title'
    BLOCK_ADDS_SWITCH_ACTIVE = '//*[@id="qa-switcher-toggle-block-ads"]/label/div'
    ICON_ADD_BLOCKER = 'qa-icon-block-ads'
    DENY_COOKIES_SWITCH = '//*[@id="qa-switcher-toggle-deny-cookies"]/label/div'
    ICON_COOKIES_SWITCH = 'qa-icon-cookies'
    BLOCK_TRACKERS_SWITCH = '//*[@id="qa-switcher-toggle-block-tracker"]/label/div'
    ICON_TRACKERS = 'qa-icon-trackers'
    DONT_SAVE_HISTORY_SWITCH = '//*[@id="qa-switcher-toggle-dont-save-history"]/label/div'
    ICON_DONT_SAVE_HISTORY = 'qa-icon-history'
    NOTIFICATION_TEXT = 'qa-notification-text'
    CLOSE_X_BUTTON = 'qa-notification-close'
    INFORMATION_TEXT = 'qa-info-block'
    INFORMATION_TEXT_AD_BLOCK = 'adblock__empty'
    FILTERS_CONDITIONS = 'filters-conditions'
    SMART_FILTERS_ICON_VPN = 'qa-icon-vpn'
    SWITCHER_BUTTON_CONNECTION = 'switcher-button'
    BUTTON_SMART_FILTERS_SAVE = 'qa-button-save'
    POP_UP_MODAL_TEXT = 'qa-modal-body-text'
    MODAL_TITLE = 'qa-modal-head-title'
    CLOSE_MODAL_WINDOW_X = 'qa-modal-block-close'
    HEAD_TITLE_SMART = 'qa-filters-head'
    DISABLE_NAME = 'disable-name'
    DEFAULT_NAME = 'default-name'
    FREE_LIST = 'free-header'
    PREMIUM_LIST = 'premium-header'
    ALBANIA_SERVER_PREMIUM = '//*[contains(text(), "Albania")]'
    FRANCE_SERVER_FREE = 'flag-icon-fr'
    BE_DEFAULT = 'qa-default-name'
    DISABLE_VPN = 'qa-disable-item'
    SMART_FILTERS_HEAD = 'smart-filters-head'
    HEAD_BUTTON = 'head-button'
    HEADED_BACK = 'smart-filters-head'
    ITEM_LABEL = 'item-label'
    TEST_COOKIES_SITE = '//*[contains(text(), "tena.ua")]'
    AddBlockingTitle = 'qa-head-blocker'
    InfoBlockFiltersEmpty = 'filters__empty'
    QuantitySites = '//*[contains(text(), "Exceptions: 1")]'
    ServerActive = 'server--active'
    Servers = 'qa-main-favorite-servers'
    FavoritesServers = 'qa-main-favorite-favorites'
    UnlockButton = 'qa-servers-button'



