class ShareLocators:
    ShareWindow = 'v-modal'
    ShareTitle = 'modal-share__title'
    CloseButton = 'modal-share__close'
    TelegramIcon = 'qa-social-icon-telegram'
    TelegramTitle = 'qa-social-text-telegram'
    WhatsAppIcon = 'qa-social-icon-whatsapp'
    WhatsAppTitle = 'qa-social-text-whatsapp'
    FacebookIcon = 'qa-social-icon-facebook'
    FacebookTitle = 'qa-social-text-facebook'
    TwitterIcon = 'qa-social-icon-twitter'
    TwitterTitle = 'qa-social-text-twitter'
    ViberIcon = 'qa-social-icon-viber'
    ViberTitle = 'qa-social-text-viber'
    RedditIcon = 'qa-social-icon-reddit'
    RedditTitle = 'qa-social-text-reddit'
    CopyLink = 'qa-copy-link'
    CopySuccess = 'v-toast'

